### ISSUE TITLE
Changer la vue d'OGSCalc

### ISSUE THREAD

**Issue by Choubakawa** [OGSteam/mod-ogscalc#2]
Hello,

En utilisant OGSCalc , j'ai un "soucis" qui revient souvent, c'est que j'ai seulement le prix pour une planète/lune. Si je veux faire l'amélioration sur plusieurs planètes je prendre un excel/calculette pour avoir le prix total de l'amélioration sur le compte.
J'ai donc pensé que si on avait la même vue que l'espace personnel mais avec des input en plus (pour les niveaux désirés), il y aurait donc tout sur une page et plus besoin d'utiliser autre chose pour avoir le prix total.

Pour illustrer mon idée:

![ogscalc](https://user-images.githubusercontent.com/30017832/39094963-d54cadc2-4638-11e8-9fe8-9a66a87f61da.jpg)

Je pense que mettre partout le prix en métal/cristal/deut n'est pas nécessaire, si les ressources sont indiquées dans les totaux (chaque catégorie et le total général) c'est suffisant.

**Comment by darknoon29** [comment]
@Choubakawa La modification me va. tu veux essayer de la faire ? Le mod est assez facile à prendre en main ;-)
