### ISSUE TITLE
Mise à jour version 2.0.1 Impossible

### ISSUE THREAD

**Issue by darknoon29** [OGSteam/mod-ogscalc#5]
Quand je lance la mise à jour elle semble s'effectuer correctement mais je restes en 2.0.0.

Sans doute un soucis du version.txt

**Comment by Choubakawa** [comment]
Non un soucis des commits associer à la release.

La version 2.0.0 et 2.0.1 ont le même commit, j'ai créé une nouvelle release sur un nouveau commit pour régler le soucis.

Je ferme :)
