### ISSUE TITLE
Récupération des planètes users + bug calcul

### ISSUE THREAD

**Issue by Athar42** [OGSteam/mod-ogscalc#6]
En version OGSpy 3.3.4 (pas vérifié en 3.3.2), si l'utilisateur n'a qu'une seule planète, dans le fichier ogscalc.php on à cette ligne (ligne 45):

`$nb_planete = find_nb_planete_user($user_data['user_id']);`

Le problème ? si on a une seule planète référencé, le retour reste à 9, ce qui créé une tonne d'erreurs "Undefined value" pour les 8 autres planètes, ce qui engendre un second bug : aucun calcul ne fonctionne !

En attendant, j'ai pu bypasser le problème, j'ai ajouté une nouvelle variable globale nommé : find_nb_planete_user_real (copie de l'existante), et j'ai supprimé simplement la "sécurité" de mettre automatiquement la valeur par défaut à 9, devant éviter des bugs d'affichage.

Une fois fait, les calculs fonctionnent, mais pas tous.
Exemple : On a une technologie énergie à 6, je veux simuler pour passer à 10 ==> Résultat : 0
Aucune mise à jour des valeurs.
Cela est valide, dans ce cas de figure pour les projets allant de 10 à 59 inclus ! Si on met en valeur de projet "60", le calcul passe à nouveau :D

Je n'ai pas encore décortiqué le code, mais à mon avis, il interprète mal la valeur du projet.

**Comment by darknoon29** [comment]
Disponible en version 2.0.5
